### ISSUE TITLE
`test_variance_of_added_perturbations_is_correct` in orquestra-vqa is non-deterministic

### ISSUE THREAD

**Issue by mstechly** [zapatacomputing/orquestra-core#11]
`test_variance_of_added_perturbations_is_correct` test in [orquestra-vqa](https://github.com/zapatacomputing/orquestra-vqa/blob/afc6250be7458e383c853eb4bf5b2164fff329c9/tests/orquestra/vqa/opt/fourier_test.py#L313) sometimes fails due to a threshold not being met in  non-deterministic test. We should update the test to be deterministic, for example by setting a seed for the random number generator.

## Additional context
You can find a failed CICD run [here](https://github.com/zapatacomputing/orquestra-vqa/runs/6389212302?check_suite_focus=true).

**Comment by divshacker** [comment]
I can try working on this. But I need some more context as I am new in this ecosystem.

**Comment by mstechly** [comment]
Oh, sorry! I have accidentally not included the link to the test in the issue description, you can find it [here](https://github.com/zapatacomputing/orquestra-vqa/blob/afc6250be7458e383c853eb4bf5b2164fff329c9/tests/orquestra/vqa/opt/fourier_test.py#L313) .

The test itself is pretty short and the function it tests is pretty well defined, so it should be relatively straightforward, but let me know if anything there is unclear.
