### ISSUE TITLE
Create `subdistribution()` function for MeasurementOutcomeDistribution

### ISSUE THREAD

**Issue by AthenaCaesura** [zapatacomputing/orquestra-core#13]
Our scientists often make use of more qubits than they measure at the end of their experiments (e.g. ancilla qubits). Currently, our `MeasurementOutcomeDistributions` (defined [here](https://github.com/zapatacomputing/orquestra-quantum/blob/main/src/orquestra/quantum/distributions/_measurement_outcome_distribution.py)) can become difficult to read if there are many other qubits that we really should just ignore.

We should solve this issue by adding a function `subdistribution()` which takes a list of qubit indices and returns the same MeasurementOutcomeDistribution with only the provided qubits. That is, we should sum all the counts associated with each outcome of the provided qubits.

@AthenaCaesura has written some [ad-hoc code](https://github.com/zapatacomputing/orquestra-qiskit/blob/main/src/orquestra/integrations/qiskit/backend/backend.py#:~:text=active_qubits.sort,(key)) to modify a dictionary of counts to exclude qubits, but it would be nice if we incorporated this into a function which is callable from the distribution itself and returns a MeasurementOutcomeDistribution.

Deliverables:

- [ ] Write `subdistribution` function as described above.
- [ ] Write tests for `subdistribution` including cases where:
  1. All the qubits remain active
  2. Input list contains qubit indices not present in the original distribution.

Affected repo: [`orquestra-quantum`](https://github.com/zapatacomputing/orquestra-quantum)

**Comment by mstechly** [comment]
@fred5825  Feel free!

**Comment by fred5825** [comment]
Awesome thank you @mstechly I was wondering if you would be at the unitaryhack office hours. So we could discuss more, I am new to hackathons and opensource, I don't know my way around much.

**Comment by fred5825** [comment]
@AthenaCaesura Awesome thank you please let me know what time you are available to chat. Also to find the UH office hours is on the top of the discord page in events.

**Comment by mstechly** [comment]
@fred5825 I added some timeslots for office hours, but it seems the website didn't auto-update yet. Keep an eye on it though!

**Comment by fred5825** [comment]
@mstechly Awesome thank you and just to confirm, you mean the UH website right?

**Comment by mstechly** [comment]
@fred5825  I mean here: https://unitary.fund/talks.html

**Comment by fred5825** [comment]
Thank you I will check it out.

**Comment by Renaud2002** [comment]
Hi @mstechly I was wondering if you could add this account to the issue the acount: fred5825 is my school account, I wanted to make the changes using me personal account. At the moment I can't commit my code because it says permission denied. Very sorry for the inconvenience.

**Comment by mstechly** [comment]
@Renaud2002 @fred5825 I can't give you write access to the repository, as you're not Zapata employee, but this is not a really problem.
You can fork the repo and make a pull request from there, just follow the procedure described [here](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) :)

**Comment by fred5825** [comment]
Yes of course I tried push it to my fork but this is the error that i encounter, I don't know why it says this
 

![Screen Shot 2022-06-15 at 6 53 30 PM](https://user-images.githubusercontent.com/101068945/173955412-a9fc4763-a6e3-4c97-bec0-57767561f8e3.png)

**Comment by fred5825** [comment]
@mstechly I think I know why the issue is happening I think I might have maybe clone the actual repository instead of my fork.

**Comment by fred5825** [comment]
@mstechly That was in fact the issue I am very sorry for the inconvenience, the pull request has been created.

**Comment by mstechly** [comment]
@fred5825  No problem! I'll take a look tomorrow!

**Comment by fred5825** [comment]
@mstechly Awesome thank you.
