### ISSUE TITLE
Create `exponential` wrapper class

### ISSUE THREAD

**Issue by AthenaCaesura** [zapatacomputing/orquestra-core#15]
## Problem
Our codebase implements gates through the [abstract `Gate` protocol](https://github.com/zapatacomputing/orquestra-quantum/blob/main/src/orquestra/quantum/circuits/_gates.py). It is common for our scientists to make use of exponentials of these gates. A simple application would be to find a [solution to the time-independent shrodinger equation](https://en.wikipedia.org/wiki/Schr%C3%B6dinger_equation#:~:text=Holding%20the%20Hamiltonian,solution%5B9%5D). Recently, we have created a new custom gate whenever we needed to raise a matrix to a power, but it would be nice to have a function which implements this directly.

## Solution Description 
Implement a class `exponential` wrapper around the `Gate` Protocol. We only need to calculate exponentials for gates without free parameters, so make sure your gate you are wrapping around does not have them. tip: `exponential` should be implemented similarly to the `dagger` wrapper class.

You will either have to test that the wrapped gate is hermitian or implement gates which are non-unitary. Currently, it isn't known whether or not gates can be non-unitary so you might have to test for yourself. 🙂 

## Deliverables
- [ ] `exponential` wrapper around `Gates` as described above.
- [ ] Write tests for above class

Affected repo: [`orquestra-quantum`](https://github.com/zapatacomputing/orquestra-quantum)

**Comment by ixime** [comment]
Hi, I would want to give it a try. Do you have office hours at unitaryhack? It's the first time I see your repo

**Comment by mstechly** [comment]
Hi @ixime ! Yes we have office hours – I have filled in the form but it doesn't show up in the calendar yet.

**Comment by mstechly** [comment]
@ixime They are now live at https://unitary.fund/talks.html

**Comment by ixime** [comment]
Thanks @mstechly !

**Comment by mstechly** [comment]
Closed by https://github.com/zapatacomputing/orquestra-quantum/pull/28
