### ISSUE TITLE
Installation of optional dependencies

### ISSUE THREAD

**Issue by VolodyaCO** [zapatacomputing/orquestra-core#37]
## Is your feature request related to a problem? If so, please describe it.
We would like to install just `orquestra-core` in `orquestra-qml-core`, but to do so we need to install `orquestra-opt[cma]`. We do not have this option with the current state of `orquestra-core`.

## How you envision the solution
Having a list of optional dependencies in the `setup.cfg` file of `orquestra-core` that would allow for all the possible combinations of optional dependencies of `orquestra-opt, orquestra-...`

## Describe alternatives you've considered
The alternative is to install `orquestra-opt` and then on top of that install `orquestra-opt[cma]`.

**Comment by VolodyaCO** [comment]
CC. @brian-dellabetta

**Comment by mstechly** [comment]
You should not use `orquestra-core` as a dependency in your projects, as most probably you don't need all the elements from `orquestra-core`.  `orquestra-core` was intended to be just a utility that allows you to quickly start tinkering with your project by installing all the deps you might need. 
Much better solution would be to just specify which packages from `orquestra-core` you really need inside your project. So in this case that would be `orquestra-opt[cma]`.

**Comment by VolodyaCO** [comment]
Understood, thanks @mstechly
